auto: true

markdown: rdiscount


#paginate: 8
permalink: /:title

name: “r1nging's Blog”
title: 's blog
description: Everything about r1nging.
url: http://r1nging.github.io
feed: /atom.xml
author_info: <a href="http://r1nging.github.io/">r1nging</a>
